# docker-compose.yml (đặt ở thư mục gốc của dự án)
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - AWS_REGION=us-east-1
      - BEDROCK_MODEL_ID=anthropic.claude-v2
      # Thêm các biến môi trường khác cần thiết
    volumes:
      - ~/.aws:/home/expressjs/.aws:ro  # Mount AWS credentials cho Bedrock
    restart: unless-stopped