services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    volumes:
      - ~/.aws:/home/expressjs/.aws:ro  # Mount AWS credentials để gọi Bedrock
    restart: unless-stopped
