# k8s/overlays/prod/aws-credentials-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: learnaws
type: Opaque
stringData:
  # Nếu bạn đã có AWS credentials trên EC2, bạn có thể mount trực tiếp
  # Hoặc bạn có thể tạo secret từ file credentials:
  credentials: |
    [default]
    aws_access_key_id=YOUR_ACCESS_KEY
    aws_secret_access_key=YOUR_SECRET_KEY
  config: |
    [default]
    region=us-east-1
    output=json