# k8s/base/frontend/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: learnaws
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: http
  type: ClusterIP