apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: learnaws-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thuatnd-rk/learnaws.click.git
    targetRevision: develop
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: learnaws-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true