apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: learnaws-dev
type: Opaque
stringData:
  credentials: |
    [default]
    aws_access_key_id=YOUR_ACCESS_KEY
    aws_secret_access_key=YOUR_SECRET_KEY
  config: |
    [default]
    region=us-east-1
    output=json