apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: learnaws
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: backend
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi