apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: learnaws
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: frontend
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi