apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: learnaws-dev

resources:
- ../../base

patchesStrategicMerge:
- frontend-patch.yaml
- backend-patch.yaml

configMapGenerator:
- name: backend-config
  behavior: merge
  literals:
  - NODE_ENV=development
  - BEDROCK_MODEL_ID=anthropic.claude-v2

images:
- name: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/learnaws-frontend:latest
  newTag: dev
- name: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/learnaws-backend:latest
  newTag: dev